[platformio]
default_envs = bw_shp6

[env:bw_shp6]
platform = espressif8266
board = esp8285
framework = arduino

monitor_speed = 115200
upload_speed = 460800

board_build.flash_mode = dout
board_build.filesystem = littlefs

build_flags =
  -D WMS_BWSHP6_CF1_GPIO=4

lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
  knolleary/PubSubClient @ ^2.8
  xoseperez/HLW8012 @ ^1.1.1
