[platformio]
default_envs = esp32dev_tft

[env:esp32dev_tft]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/pio_ota_pubkey.py

monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB

board_build.filesystem = littlefs
board_build.partitions = partitions_esp32_16m_tft.csv

lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
  knolleary/PubSubClient @ ^2.8
  esp32async/ESPAsyncWebServer @ ^3.9.6
  esp32async/AsyncTCP @ ^3.4.10
  adafruit/Adafruit GFX Library @ ^1.12.5
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0

[env:esp32c6_tft_test]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
extra_scripts = pre:scripts/pio_ota_pubkey.py

monitor_speed = 115200
upload_speed = 115200
upload_flags = --no-stub

board_build.filesystem = littlefs
board_build.partitions = partitions_c6_tft_test_4m.csv

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DWMS_BOARD_ESP32C6_RELAY_X1_V11

lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
  knolleary/PubSubClient @ ^2.8
  esp32async/ESPAsyncWebServer @ ^3.9.6
  esp32async/AsyncTCP @ ^3.4.10
  adafruit/Adafruit GFX Library @ ^1.12.5
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
